controller_list:
  - name: j2s6s200_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_j2s6s200_joint_1
      - robot_j2s6s200_joint_2
      - robot_j2s6s200_joint_3
      - robot_j2s6s200_joint_4
      - robot_j2s6s200_joint_5
      - robot_j2s6s200_joint_6
  - name: j2s6s200_gripper_controller
    action_ns: gripper_command
    type: GripperCommand
#    action_ns: follow_joint_trajectory
    default: True
#    type: FollowJointTrajectory
    joints:
      - robot_j2s6s200_joint_finger_1
      - robot_j2s6s200_joint_finger_2
