controller_list:
  - name: fake_j2s6s300_arm_controller
    joints:
      - robot_j2s6s300_joint_1
      - robot_j2s6s300_joint_2
      - robot_j2s6s300_joint_3
      - robot_j2s6s300_joint_4
      - robot_j2s6s300_joint_5
      - robot_j2s6s300_joint_6
  - name: fake_j2s6s300_gripper_controller
    joints:
      - robot_j2s6s300_joint_finger_1
      - robot_j2s6s300_joint_finger_tip_1
      - robot_j2s6s300_joint_finger_2
      - robot_j2s6s300_joint_finger_tip_2
      - robot_j2s6s300_joint_finger_3
      - robot_j2s6s300_joint_finger_tip_3