# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: j2s6s300_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_j2s6s300_joint_1
    - robot_j2s6s300_joint_2
    - robot_j2s6s300_joint_3
    - robot_j2s6s300_joint_4
    - robot_j2s6s300_joint_5
    - robot_j2s6s300_joint_6
    - robot_j2s6s300_joint_finger_1
    - robot_j2s6s300_joint_finger_tip_1
    - robot_j2s6s300_joint_finger_2
    - robot_j2s6s300_joint_finger_tip_2
    - robot_j2s6s300_joint_finger_3
    - robot_j2s6s300_joint_finger_tip_3
    - robot_back_left_wheel_joint
    - robot_back_right_wheel_joint
    - robot_front_left_wheel_joint
    - robot_front_right_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: j2s6s300_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_j2s6s300_joint_1
      - robot_j2s6s300_joint_2
      - robot_j2s6s300_joint_3
      - robot_j2s6s300_joint_4
      - robot_j2s6s300_joint_5
      - robot_j2s6s300_joint_6
  - name: j2s6s300_gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_j2s6s300_joint_finger_1
      - robot_j2s6s300_joint_finger_tip_1
      - robot_j2s6s300_joint_finger_2
      - robot_j2s6s300_joint_finger_tip_2
      - robot_j2s6s300_joint_finger_3
      - robot_j2s6s300_joint_finger_tip_3